config/routes.rb
Rails.application.routes.draw do

  get 'administrater/main'
  root  'homepage#index'
  # get 'demo/index'

  get 'homepage/test'
  get 'accounts/test'
  # get "login", to: "homepage#login"
  # get "register", to: "homepage#register"
  get 'accounts/login'
  get 'accounts/register'
  post 'create_account' => 'accounts#create_account'
  post 'create_login' => 'accounts#create_login'
  # get 'homepage/Register'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  ROLE = {0 => "customer", 1 => "admin", 2 => "super admin"}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def login

  end

  def register
    @account = Account.new
  end

  # def test
  #   email = params[:email].strip
  #     role = params[:role].strip
  #     if role.to_i == 0
  #       @str2=email
  #       end
  # end


def  create_account
  # params ={:account => :name}
  # params ={:account => :email}
  # params ={:account => :password}
  # params ={:account => :password_confirm}
  # params ={:account => :role}
  puts "test_2"
  name = params[:account][:name]
  email = params[:account][:email]
  password = params[:account][:password]
  password_confirmation = params[:account][:password_confirmation]
  role = params[:account][:role]

  #setting account status, admin can control it。 1 is non-activated, 0 is activated.
  #set role , 0 is customer, 1 is admin , 2 is super-admin. design this for super-admin to specify admin.
  # Limit registration authority， only super-admin can specify admin.
  status = 0
  if role.to_i == 1
    status = 1
  end

  # get data from database for next step check the email address and name was registered or not.
  account_n = Account.find_by(name:name)
  account_e = Account.find_by(email:email)

  # create an account
  @account = Account.new

  if name.blank? || email.blank?

    redirect_to "/accounts/register", notice: ": user name or email can not empty"
  elsif  account_n
    redirect_to "/accounts/register", notice: ": user name has been registered"

    puts "account1"
  elsif  account_e
    redirect_to "/accounts/register", notice: ": email address already  be registered"

    puts "account2"
  elsif  name.length >10
    redirect_to "/accounts/register", notice: ": User name can not longer than 10 letters"
  elsif password.blank? || password_confirmation.blank?

    redirect_to "/accounts/register", notice: ": password empty!"

  elsif  password != password_confirmation
    redirect_to "/accounts/register", danger: ": The passwords were not entered in the same way"
  else
    @account.status = status
    @account.name = name
    @account.email = email
    @account.password = password
    @account.role = role
    boolean = @account.save
    if boolean
      flash[:notice] =  "Register successful"
       redirect_to "/homepage/test"
    else
      flash[:notice] =  "Register failed"
      render :register
    end
  end
end

  def create_login
    # take info from login page params
    email = params[:email].strip
    password_html = params[:password].strip
    # check the input area empty or not

    # if email.blank? || password_html.blank?
    #   flash[:Notice] = ": Email address or password empty"
    #   redirect_to "/accounts/login"
    # end
    #use email to find user
    account = Account.find_by(email:email)

    #if the user exist
    if account
      #user is admin，status active，password correct，then login successful
      if account.role == 1 && account.status == 0
        #compare input password to database password
        if account.password.to_s == password_html
          redirect_to  "/administrater/main", notice: "Login successful"
        else
          flash.notice = "User name or password incorrect!"
          redirect_to "/accounts/login", notice: ": User name or password incorrect!"
        end
        #if user is admin，status non-active，need active by super-admin
      elsif account.role == 1 && account.status == 1
        flash.notice = ": account not activate, please contact super-admin"
        redirect_to "/accounts/login"
        #normal user, password correct. login
      else
        if account.password.to_s == password_html
          # session[:account_id] = account.id
          flash.notice = "Login successfully！"
          redirect_to "/homepage/test"
        else
          flash.notice = "User name or password incorrect!"
          render :login
        end
      end
      #if user not exist, notice user to register
     elsif
       email.blank? || password_html.blank?
        flash[:Notice] = ": Email address or password empty"
        redirect_to "/accounts/login"

      # flash.notice = "user not exist, register now"
      else
      redirect_to "/accounts/login", Notice: ": User not exist, register now !"
    end
    end




  # def test
  #   email = params[:account][:email]
  #   role = params[:account][:role]
  #   if role.to_i == 0
  #     @str2=email.to_s
  #   end
  # end
  def test
  end
end

app/controllers/administrater_controller.rb
class AdministraterController < ApplicationController
  def main
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @str1 = "say"
  end
  # def test
  #  @accounts = Account.find_by_role("0")
  #   email = params[:email].strip
  #   role = params[:role].strip
  #   if role.to_i == 0
  #     @str2=email
  #   end
  #
  # end

  # def login
  #
  # end
  # def register
  #
  # end







end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/administrater_helper.rb
module AdministraterHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/accounts/login.html.erb
<!--<div class="jumbotron jumbotron-fluid">-->
<!--  <div class="container">-->
<!--    <p>Email Address:</p><%#= text_field_tag(:email, params[:email]) %><br />-->
<!--    <p>Password:</p><%#= password_field_tag(:password, params[:password]) %><br />-->

<!--    <dd><%#= submit_tag "Login" %></dd><br />-->
<!--    <div class="need-login">-->
      <%#= link_to "Do not have account? register now！", "/register" %>
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
<div class="container">
  <% flash.each do |name,msg|  %>
    <div class='alert alert-danger'>
      <%= name %>
      <%= msg %>
    </div>
  <% end %>
</div>
<div class="jumbotron jumbotron-fluid">
<div class="Login-form-container">
  <div class="Login-form">
    <%= form_tag "/create_login" do %>
      <dl class="form">
        <dt>
          <%= label_tag"Email" %>
        </dt>
        <dd>
          <%= text_field_tag :email,params[:email] %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
          <%= label_tag"password" %>
        </dt>
        <dd>
          <%= password_field_tag :password,params[:password] %>
        </dd>
      </dl>
      <p><%= submit_tag "Login", :class=>"login-button btn btn-primary" %></p>
      <% end %>
      </div>
  </div>
</div>
<dl>
  <dt>Coffee</dt>
  <dd>Black hot drink</dd>
  <dt>Milk</dt>
  <dd>White cold drink</dd>
</dl>

app/views/accounts/register.html.erb
<%# flash.each do |password,password_confirmation|  %>
<!--  <div class='alert alert-danger'>-->
    <%#= password %>
    <%#= password_confirmation %>
<!--  </div>-->
<%# end %>

<div class="jumbotron jumbotron-fluid">
  <h2 style="color: lightseagreen">Start your new trip on Maptek</h2>
<!--  set notice-->
  <div class="container">
    <% flash.each do |name,msg|  %>
      <div class='alert alert-danger'>
        <%= name %>
        <%= msg %>
      </div>
    <% end %>
  </div>
<!--  input info-->
  <div class="Register-form-container clearfix">
  <div class="Register-form">

    <%= form_for @account,url:"/create_account" do |f| %>
      <dl class="form">
        <dt><%= f.label :name, "User Name(less than ten characters)" %></dt>
        <dd><%= f.text_field :name %></dd>

      </dl>
      <dl class="form">
        <dt><%= f.label :email %></dt>
        <dd><%= f.text_field :email %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :password, "Password" %></dt>
        <dd><%= f.password_field :password %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :password_confirmation, "Confirm Password" %></dt>
        <dd><%= f.password_field :password_confirmation %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :role, "Role" %></dt>
        <dd>
          <select name="account[role]" class="form-control" >
            <% Account::ROLE.each do |ro| %>
              <option value= "<%= ro[0] %>"><%= ro[1] %></option>
            <% end %>
          </select>
        </dd>
      </dl>
      <p><%= f.submit "Register", :class => "Register-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>
</div>

app/views/accounts/test.html.erb
<h1>Testing</h1>


<%= image_tag("logos/puppy.jpg") %>
<%= image_tag("logos/puppy1.jpg") %>

app/views/administrater/main.html.erb
<div class="jumbotron jumbotron-fluid">
  <h1 style = "color: darkorange">Welcome to Administrator Page</h1>
  <p>In this page, you can manage the exam for candidates，review the exam and edit the questions !</p>
  <a class="btn btn-primary" href="/homepage/test" role="button">Choose Candidates</a>
  <a class="btn btn-primary" href="/accounts/test" role="button">Review Exam</a>
  <a class="btn btn-primary" href="/homepage/test" role="button">Edit Questions</a>
  <h3>Candidates Email Address:</h3>
<!--  <p>-->
    <%# Account.all.each do |email| %>
    <%#= email.email%>
  <%# end %>
<!--  </p>-->

  <table>
    <tr>
      <th>Candidates</th>

    </tr>
    <% Account.all.each do |account| %>
      <tr>
        <td>  <%= check_box_tag(:candidates,"email") %></td>

        <td ><d style="color: orangered">User name  </d><%= account.name %></td>
        <td><d style="color: orangered">Email address </d><%= account.email %></td>
      </tr>
    <% end %>
  </table>



</div>

app/views/homepage/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to Maptek</h1>
  <p class="lead">Maptek™ is a leading provider of innovative software, hardware and services for the mining industry. Founded 38 years ago, Maptek develops products which are used at more than 2000 sites in 85 countries. Products cover the whole mining cycle from exploration to reclamation..</p>
  <hr class="my-4">
<!--  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>-->
  <a class="btn btn-primary" href="accounts/login" role="button">Login</a>

  <a class="btn btn-primary" href="accounts/register" role="button">Register</a>
  <a class="btn btn-primary" href="accounts/test" role="button">Test</a>



</div>



<div class = 'jumbotron center' >
<!--<h1 class ="title">Welcome to Maptek</h1>-->
<%#str = "Login" %>
  <!--  change text color command-->

 <p style = "color:blue"> <%= "Just wanna  #{@str1} something !!!" %> </p>


  <%#= link_to "home", root_path %>
<!--<p> <%#= link_to "Contact us","https://www.maptek.com/contact/index.html/" %></p>-->

<!--  this method show the full address, use for mail-->
<!--  <p> <%#= link_to "login", login_url %> </p>-->

<!--<a href="register">Register a new account</a>-->
</div>

app/views/homepage/login.html.erb
<!--<div class="jumbotron jumbotron-fluid">-->
<!--  <div class="container">-->
<!--    <p>Email Address:</p><%#= text_field_tag(:email, params[:email]) %><br />-->
<!--    <p>Password:</p><%#= password_field_tag(:password, params[:password]) %><br />-->

<!--    <dd><%#= submit_tag "Login" %></dd><br />-->
<!--    <div class="need-login">-->
      <%#= link_to "Do not have account? register now！", "/register" %>
<!--  </div>-->
<!--</div>-->
<!--</div>-->

app/views/homepage/register.html.erb
<h1 style="color: gold">Register your new account !</h1>




<!--<p>Name:</p><%#= text_field(:person, :name) %>-->

<!--<p>Email Address:</p><%#= text_field(:person, :email_field) %>-->
<!--<p>Password:</p><%#= password_field_tag(:password) %>-->
<!--<p>Confirm password:</p><%#= password_field_tag(:password) %>-->
<!--<p>What position you want to apply?(multiple-choice)</p>-->

<%#= check_box_tag(:job_font) %>
<%#= label_tag(:job_font, "Software Engineering") %>
<%#= check_box_tag(:job_back) %>
<%#= label_tag(:job_back, "System Architecture") %>
<%#= check_box_tag(:job_data) %>
<%#= label_tag(:job_data, "Data Analysis") %>
<%#= check_box_tag(:job_design) %>
<%#= label_tag(:job_design, "Web Development") %>

<!--<p>(This is an optional question)</p>-->
<%#= radio_button_tag(:age, "child") %>
<%#= label_tag(:age_child, "I am younger than 21") %>
<%#= radio_button_tag(:age, "adult") %>
<%#= label_tag(:age_adult, "I'm over 21") %>
<%#= radio_button_tag(:age, "adult+") %>
<%#= label_tag(:age_adult, "I'm over 35") %>



<!--<p><%#=button_tag "Submit" %></p>-->


<div class="Register-form-container clearfix">
  <div class="Register-form">
    <%= form_for @account,url:"/create_account" do |f| %>
      <dl class="form">
        <dt><%= f.label :name, "User Name(less than ten characters)" %></dt>
        <dd><%= f.text_field :name %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :email %></dt>
        <dd><%= f.text_field :email %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :password, "Password" %></dt>
        <dd><%= f.password_field :password %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :password_confirmation, "Confirm Password" %></dt>
        <dd><%= f.password_field :password_confirmation %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :role, "Role" %></dt>
        <dd>
          <select name="account[role]" class="form-control" >
            <% Account::ROLE.each do |ro| %>
              <option value= "<%= ro[0] %>"><%= ro[1] %></option>
            <% end %>
          </select>
        </dd>
      </dl>
      <p><%= f.submit "Register", :class => "Register-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/homepage/test.html.erb
<div class="jumbotron jumbotron-fluid">
<h2 style="color: darkorange">Welcome to Test page</h2>
  <h2 style="color: blue">This page is for candidates exam</h2>
  <h3>Question 1:</h3>
  <b>Please use Ruby to write an </b><b style="color: #B00100"> Mathematical function</b>
  <b>which can realize Sum = X + Y.</b>

<div class="jumbotron jumbotron-fluid">
  <h3>Please input your code  blow </h3>
<div class="col-sm-10 controls">
  <textarea class="form-control" name="description" cols="50" rows="20" placeholder="Code text" data-fv-field="description"></textarea>
  <i class="form-control-feedback" data-fv-icon-for="description" style="display: none;"></i>
</div>
</div>
  <%= button_tag "Submit" %>
</div>

app/views/layouts/_footer.html.erb
<div class="card-body">
  <h5 class="card-title">This is a footer</h5>
  <p class="card-text">Add some information for future</p>
  <a href="#" class="btn btn-primary">Go somewhere</a>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maptek Hiring</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



<!--<div>-->
<!-- <%= link_to "  <p style='color: black;'>Home</p>-->
".html_safe, root_path %>

  <%#= link_to "https://www.maptek.com/about_maptek/index.html" do %>
<!-- <p style='color:black;'>About us</p>-->
    <%#end %>

<!--<%= link_to "<p style='color: black;'>Contact us</p>-->
".html_safe,"https://www.maptek.com/contact/index.html/" %>
<!--</div>-->
  <%#= form_tag("/search", method: "get") do %>
    <%#= label_tag(:q, "Search for:") %>
    <%#= text_field_tag(:q) %>
    <%#= submit_tag("Search") %>
  <%# end %>



<nav class="navbar navbar-dark bg-dark"></nav>
<div class="card text-center">
  <div class="card-header" style="background-color: darkgray;">
    <%= link_to image_tag("logos/Maptek_logo.png", alt: "Rails logo"),
                'https://www.maptek.com/',id: "mtlogo"%>
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.maptek.com/about_maptek/index.html">About us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.maptek.com/contact/index.html" tabindex="-1" aria-disabled="true">Contact us</a>
      </li>
    </ul>
  </div>
</div>



  <%= yield %>
  </body>
<%= render partial: 'layouts/footer' %>
</html>